version: '3'

tasks:
  default:
    cmds:
      - go build -o timr ./cmd/timr
  run:
    cmds:
      - go run ./cmd/timr
  test:
    cmds:
      - go test ./...
  install:
    cmds:
      - go install ./cmd/timr
