complete -c timr -n "__fish_use_subcommand" -a start -d "Start the timer"
complete -c timr -n "__fish_use_subcommand" -a stop -d "Stop the timer"
complete -c timr -n "__fish_use_subcommand" -a pause -d "Pause the timer"
complete -c timr -n "__fish_use_subcommand" -a status -d "Show the timer status"
complete -c timr -n "__fish_use_subcommand" -a reset -d "Reset the timer"
complete -c timr -n "__fish_use_subcommand" -a live -d "Show the live timer"
complete -c timr -n "__fish_use_subcommand" -a prompt -d "Show the prompt status"
